# Site settings
title: Max Depth
description: '"the maximum operating depth of a breathing gas is the depth below which the partial pressure of oxygen of the gas mix exceeds an acceptable limit"'
url: 'http://maxdepth.io'
baseurl: ''
google_analytics: 'UA-111640496-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Will Tome'
  #email: will@maxdepth.io
  twitter_username: willtome
  github_username:  willtome
  linkedin_username:  willtome

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']


github_comments_repository: willtome/maxdepth.io